apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - supersonic/helmrelease.yaml
  - supersonic-dynamic/helmrelease.yaml
  - supersonic-interlink/helmrelease.yaml
  - gitrepo.yaml
  - helmrepo.yaml
  - prometneus-networkpolicy.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: supersonic-config
    files:
      - values.yaml=supersonic/values.yaml
  - name: supersonic-dynamic-config
    files:
      - values.yaml=supersonic-dynamic/values.yaml
  - name: supersonic-interlink-config
    files:
      - values.yaml=supersonic-interlink/values.yaml
