apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-sonic
  namespace: sonic
  annotations:
    cluster: geddes
spec:
  interval: 1m
  timeout: 1m
  path: "./resources/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: sonic-git-repo
  targetNamespace: sonic
